# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Artist.create(name: "Drake" )
Artist.create(name: "Kanye West" )
Artist.create(name: "Big Sean" )
Artist.create(name: "Ed Sheeran" )
Artist.create(name: "Maroon 5" )
Artist.create(name: "Nicki Minaj" )
Artist.create(name: "The Weeknd" )
Artist.create(name: "Sam Smith" )
Artist.create(name: "Fall Out Boy" )
Artist.create(name: "Chris Brown" )
Artist.create(name: "Eminem" )
Artist.create(name: "Beyonce" )
Artist.create(name: "Ariana Grande" )
Artist.create(name: "Rihanna" )
Artist.create(name: "J. Cole" )
Artist.create(name: "Imagine Dragons" )
Artist.create(name: "Ellie Goulding" )
Artist.create(name: "One Direction" )
Artist.create(name: "Hozier" )
Artist.create(name: "JAY Z" )
Artist.create(name: "Wiz Khalifa" )
Artist.create(name: "Skrillex" )
Artist.create(name: "Lana Del Ray" )
Artist.create(name: "Calvin Harris" )
Artist.create(name: "Coldplay" )
Artist.create(name: "Sia" )
Artist.create(name: "Ne-Yo" )
Artist.create(name: "Kelly Clarkson" )
Artist.create(name: "Pitbull" )
Artist.create(name: "Lil Wayne" )
Artist.create(name: "Kenrick Lamar" )
Artist.create(name: "Meghan Trainor" )
Artist.create(name: "Usher" )
Artist.create(name: "John Mayer" )
Artist.create(name: "Luke Bryan" )
Artist.create(name: "Katy Perry" )
Artist.create(name: "Childish Gambino" )
Artist.create(name: "Mark Ronson" )
Artist.create(name: "Diplo" )
Artist.create(name: "Tigers Jaw" )
Artist.create(name: "Blink-182" )
Artist.create(name: "Brand New" )
Artist.create(name: "Paul McCartney" )
Artist.create(name: "The Beatles" )
Artist.create(name: "Flo Rida" )
Artist.create(name: "Fifth Harmony" )
Artist.create(name: "Trey Songz" )
Artist.create(name: "Bruno Mars" )
Artist.create(name: "Florida Georgia Line" )
Artist.create(name: "Linkin Park" )
Artist.create(name: "Arctic Monkeys" )
Artist.create(name: "Sam Hunt" )
Artist.create(name: "Kid Cudi" )
Artist.create(name: "Rae Sremmurd" )
Artist.create(name: "Kid Ink" )
Artist.create(name: "David Guetta" )
Artist.create(name: "Tove Lo" )
Artist.create(name: "OneRepublic" )
Artist.create(name: "Red Hot Chili Peppers" )
Artist.create(name: "Purity Ring" )
Artist.create(name: "Tegan & Sara" )
Artist.create(name: "G-Eazy" )
Artist.create(name: "Jack Johnson" )
Artist.create(name: "Avicii" )
Artist.create(name: "Nick Jonas" )
Artist.create(name: "Romeo Santos" )
Artist.create(name: "Walk the Moon" )
Artist.create(name: "Panic! At The Disco" )
Artist.create(name: "Mumford & Sons" )
Artist.create(name: "Justin Timberlake" )
Artist.create(name: "John Legend" )
Artist.create(name: "alt-J" )
Artist.create(name: "Iggy Azalea" )
Artist.create(name: "T.I." )
Artist.create(name: "Blake Shelton" )
Artist.create(name: "Vance Joy" )
Artist.create(name: "Kevin Gates" )
Artist.create(name: "Eric Church" )
Artist.create(name: "Lorde" )
Artist.create(name: "Florence + The Machine" )
Artist.create(name: "Modest Mouse" )
Artist.create(name: "Michael Jackson" )
Artist.create(name: "5 Seconds of Summer" )
Artist.create(name: "Zedd" )
Artist.create(name: "Jessie J" )
Artist.create(name: "Jason Derulo" )
Artist.create(name: "Led Zeppelin" )
Artist.create(name: "A$AP Rocky" )
Artist.create(name: "Alesso" )
Artist.create(name: "Paramore" )
Artist.create(name: "Bon Iver" )
Artist.create(name: "Zac Brown Band" )
Artist.create(name: "Tim McGraw" )
Artist.create(name: "The Black Keys" )
Artist.create(name: "Green Day" )
Artist.create(name: "Mr. Probz" )
Artist.create(name: "Schoolboy Q" )
Artist.create(name: "Miley Cyrus" )
Artist.create(name: "Kenny Chesney" )
Artist.create(name: "Adele" )
Artist.create(name: "Bob Marley & The Wailers" )
Artist.create(name: "The Menzingers" )
Artist.create(name: "Taking Back Sunday" )
Artist.create(name: "Dessa" )
Artist.create(name: "P.O.S." )
Artist.create(name: "Whole Wheat Bread" )
Artist.create(name: "Manchester Orchestra" )
Artist.create(name: "Kevin Devine" )
Artist.create(name: "Mansions" )
Artist.create(name: "Modern Baseball" )
Artist.create(name: "The Front Bottoms" )
